"""empty message

Revision ID: cc06e6edc796
Revises:
Create Date: 2025-05-30 03:30:24.836521

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "cc06e6edc796"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "establishments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "tags",
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.PrimaryKeyConstraint("name"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("is_admin", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "establishment_tags",
        sa.Column("establishment_id", sa.Integer(), nullable=False),
        sa.Column("tag_name", sa.String(length=50), nullable=False),
        sa.Column("count", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["establishment_id"],
            ["establishments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tag_name"],
            ["tags.name"],
        ),
        sa.PrimaryKeyConstraint("establishment_id", "tag_name"),
    )
    op.create_table(
        "tag_relationships",
        sa.Column("source_tag_name", sa.String(length=50), nullable=False),
        sa.Column("target_tag_name", sa.String(length=50), nullable=False),
        sa.Column("weight", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["source_tag_name"],
            ["tags.name"],
        ),
        sa.ForeignKeyConstraint(
            ["target_tag_name"],
            ["tags.name"],
        ),
        sa.PrimaryKeyConstraint("source_tag_name", "target_tag_name"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tag_relationships")
    op.drop_table("establishment_tags")
    op.drop_table("users")
    op.drop_table("tags")
    op.drop_table("establishments")
    # ### end Alembic commands ###
